import type { ToolCardData } from '@/types';

export const TOOL_CATEGORIES = {
    convert: {
        name: 'Convert',
        color: 'from-blue-500 to-cyan-500',
    },
    organize: {
        name: 'Organize',
        color: 'from-purple-500 to-pink-500',
    },
    optimize: {
        name: 'Optimize',
        color: 'from-green-500 to-emerald-500',
    },
    edit: {
        name: 'Edit',
        color: 'from-orange-500 to-red-500',
    },
    secure: {
        name: 'Secure',
        color: 'from-indigo-500 to-purple-500',
    },
    ai: {
        name: 'AI Tools',
        color: 'from-yellow-400 to-orange-500',
    },
};

export const TOOLS: ToolCardData[] = [
    // Convert
    {
        id: 'pdf-to-word',
        title: 'PDF to Word',
        description: 'Convert PDF documents to editable Word files',
        icon: '📄',
        category: 'convert',
        href: '/pdf-to-word',
        color: 'blue',
    },
    {
        id: 'word-to-pdf',
        title: 'Word to PDF',
        description: 'Convert Word documents to PDF format',
        icon: '📝',
        category: 'convert',
        href: '/word-to-pdf',
        color: 'blue',
    },
    {
        id: 'pdf-to-excel',
        title: 'PDF to Excel',
        description: 'Extract tables from PDF to Excel spreadsheets',
        icon: '📈',
        category: 'convert',
        href: '/pdf-to-excel',
        color: 'blue',
    },
    {
        id: 'pdf-to-jpg',
        title: 'PDF to JPG',
        description: 'Convert PDF pages to high-quality JPG images',
        icon: '🖼️',
        category: 'convert',
        href: '/pdf-to-jpg',
        color: 'blue',
    },
    {
        id: 'jpg-to-pdf',
        title: 'JPG to PDF',
        description: 'Convert images to PDF documents',
        icon: '📷',
        category: 'convert',
        href: '/jpg-to-pdf',
        color: 'blue',
    },
    {
        id: 'pdf-to-xml',
        title: 'PDF to XML',
        description: 'Convert PDF content to structured XML data',
        icon: '🔗',
        category: 'convert',
        href: '/pdf-to-xml',
        color: 'blue',
    },
    {
        id: 'image-to-pdf',
        title: 'Image to PDF',
        description: 'Convert any image format to PDF',
        icon: '🎨',
        category: 'convert',
        href: '/image-to-pdf',
        color: 'blue',
    },

    // Organize
    {
        id: 'merge',
        title: 'Merge PDF',
        description: 'Combine multiple PDFs into one document',
        icon: '🔗',
        category: 'organize',
        href: '/merge',
        color: 'purple',
    },
    {
        id: 'split',
        title: 'Split PDF',
        description: 'Extract pages or split PDF into multiple files',
        icon: '✂️',
        category: 'organize',
        href: '/split',
        color: 'purple',
    },
    {
        id: 'reorder',
        title: 'Reorder Pages',
        description: 'Rearrange pages in your PDF document',
        icon: '🔄',
        category: 'organize',
        href: '/reorder',
        color: 'purple',
    },
    {
        id: 'delete-pages',
        title: 'Delete Pages',
        description: 'Remove unwanted pages from PDF',
        icon: '🗑️',
        category: 'organize',
        href: '/delete-pages',
        color: 'purple',
    },

    // Optimize
    {
        id: 'compress',
        title: 'Compress PDF',
        description: 'Reduce PDF file size while maintaining quality',
        icon: '🗜️',
        category: 'optimize',
        href: '/compress',
        color: 'green',
    },
    {
        id: 'repair',
        title: 'Repair PDF',
        description: 'Fix corrupted or damaged PDF files',
        icon: '🔧',
        category: 'optimize',
        href: '/repair',
        color: 'green',
    },

    // Edit
    {
        id: 'rotate',
        title: 'Rotate PDF',
        description: 'Rotate pages in your PDF document',
        icon: '↻',
        category: 'edit',
        href: '/rotate',
        color: 'orange',
    },
    {
        id: 'watermark',
        title: 'Add Watermark',
        description: 'Add text or image watermarks to PDF',
        icon: '💧',
        category: 'edit',
        href: '/watermark',
        color: 'orange',
    },
    {
        id: 'page-numbers',
        title: 'Page Numbers',
        description: 'Add page numbers to your PDF',
        icon: '🔢',
        category: 'edit',
        href: '/page-numbers',
        color: 'orange',
    },
    {
        id: 'ocr',
        title: 'OCR PDF',
        description: 'Extract text from scanned PDFs',
        icon: '👁️',
        category: 'edit',
        href: '/ocr',
        color: 'orange',
    },

    // Secure
    {
        id: 'protect',
        title: 'Protect PDF',
        description: 'Add password protection to your PDF',
        icon: '🔒',
        category: 'secure',
        href: '/protect',
        color: 'indigo',
    },
    {
        id: 'unlock',
        title: 'Unlock PDF',
        description: 'Remove password from PDF documents',
        icon: '🔓',
        category: 'secure',
        href: '/unlock',
        color: 'indigo',
    },
    // AI Tools
    {
        id: 'smart-convert',
        title: 'Smart AI Convert',
        description: 'Convert any file to any format with AI intelligence',
        icon: '🧠',
        category: 'ai',
        href: '/ai-convert',
        color: 'yellow',
    },
];
