import type { ToolCardData } from '@/types';

export const TOOL_CATEGORIES = {
    document: {
        name: 'Document & Word',
        color: 'from-blue-600 to-cyan-500',
    },
    data: {
        name: 'Data & Spreadsheets',
        color: 'from-green-600 to-emerald-500',
    },
    image: {
        name: 'Images & Graphics',
        color: 'from-purple-600 to-pink-500',
    },
    ai: {
        name: 'AI & Intelligence',
        color: 'from-orange-500 to-red-600',
    },
    dev: {
        name: 'Developer Tools',
        color: 'from-slate-700 to-slate-900',
    },
    web: {
        name: 'Web & Markup',
        color: 'from-indigo-500 to-purple-600',
    },
    organize: {
        name: 'Organize & Archive',
        color: 'from-purple-500 to-indigo-500',
    },
    optimize: {
        name: 'Optimize & Repair',
        color: 'from-emerald-500 to-teal-600',
    },
    edit: {
        name: 'Edit & Page Ops',
        color: 'from-orange-400 to-red-500',
    },
    secure: {
        name: 'Security & Legal',
        color: 'from-indigo-600 to-blue-700',
    },
    media: {
        name: 'Media & Video',
        color: 'from-red-500 to-pink-600',
    }
};

export const TOOLS: ToolCardData[] = [
    // === DOCUMENT & WORD ===
    {
        id: 'pdf-to-word',
        title: 'PDF to Word',
        description: 'Convert PDF documents to editable DOCX files',
        icon: '📄',
        category: 'document',
        href: '/pdf-to-word',
        color: 'blue',
    },
    {
        id: 'word-to-pdf',
        title: 'Word to PDF',
        description: 'Convert DOCX documents to professional PDF',
        icon: '📝',
        category: 'document',
        href: '/word-to-pdf',
        color: 'blue',
    },
    {
        id: 'pdf-to-ppt',
        title: 'PDF to PPTX',
        description: 'Convert PDF to editable PowerPoint slides',
        icon: '📊',
        category: 'document',
        href: '/pdf-to-ppt',
        color: 'blue',
    },
    {
        id: 'ppt-to-pdf',
        title: 'PPTX to PDF',
        description: 'Convert presentations to PDF format',
        icon: '📉',
        category: 'document',
        href: '/ppt-to-pdf',
        color: 'blue',
    },
    {
        id: 'pdf-to-txt',
        title: 'PDF to Text',
        description: 'Extract raw text from PDF documents',
        icon: '🔤',
        category: 'document',
        href: '/pdf-to-txt',
        color: 'blue',
    },
    {
        id: 'epub-to-pdf',
        title: 'EPUB to PDF',
        description: 'Convert ebooks to PDF format',
        icon: '📚',
        category: 'document',
        href: '/epub-to-pdf',
        color: 'blue',
    },

    // === DATA & SPREADSHEETS ===
    {
        id: 'pdf-to-excel',
        title: 'PDF to Excel',
        description: 'Extract tables from PDF to XLSX spreadsheets',
        icon: '📈',
        category: 'data',
        href: '/pdf-to-excel',
        color: 'green',
    },
    {
        id: 'excel-to-pdf',
        title: 'Excel to PDF',
        description: 'Convert XLSX spreadsheets to PDF tables',
        icon: '📊',
        category: 'data',
        href: '/excel-to-pdf',
        color: 'green',
    },
    {
        id: 'csv-to-json',
        title: 'CSV to JSON',
        description: 'Convert spreadsheet data to JSON objects',
        icon: '📦',
        category: 'data',
        href: '/csv-to-json',
        color: 'green',
    },
    {
        id: 'excel-to-csv',
        title: 'Excel to CSV',
        description: 'Convert Excel files to plain text CSV',
        icon: '📄',
        category: 'data',
        href: '/excel-to-csv',
        color: 'green',
    },

    // === IMAGES & GRAPHICS ===
    {
        id: 'pdf-to-jpg',
        title: 'PDF to JPG',
        description: 'Extract images or convert pages to JPG',
        icon: '🖼️',
        category: 'image',
        href: '/pdf-to-jpg',
        color: 'pink',
    },
    {
        id: 'jpg-to-pdf',
        title: 'JPG to PDF',
        description: 'Convert images to a single PDF document',
        icon: '📷',
        category: 'image',
        href: '/jpg-to-pdf',
        color: 'pink',
    },
    {
        id: 'png-to-webp',
        title: 'PNG to WebP',
        description: 'Convert PNG to next-gen WebP format',
        icon: '🌐',
        category: 'image',
        href: '/png-to-webp',
        color: 'pink',
    },
    {
        id: 'svg-to-png',
        title: 'SVG to PNG',
        description: 'Convert vector SVG to raster PNG',
        icon: '🎨',
        category: 'image',
        href: '/svg-to-png',
        color: 'pink',
    },

    // === AI & INTELLIGENCE ===
    {
        id: 'ocr-pdf',
        title: 'AI OCR PDF',
        description: 'Turn scanned PDFs into searchable text',
        icon: '👁️',
        category: 'ai',
        href: '/ocr',
        color: 'orange',
    },
    {
        id: 'invoice-to-data',
        title: 'Invoice Extractor',
        description: 'AI-powered structured data from invoices',
        icon: '💰',
        category: 'ai',
        href: '/invoice-to-data',
        color: 'orange',
    },
    {
        id: 'handwriting-to-text',
        title: 'Handwriting AI',
        description: 'Convert handwritten notes to digital text',
        icon: '✍️',
        category: 'ai',
        href: '/handwriting-to-text',
        color: 'orange',
    },
    {
        id: 'translate-doc',
        title: 'Doc Translator',
        description: 'Translate any document to 100+ languages',
        icon: '🌍',
        category: 'ai',
        href: '/translate',
        color: 'orange',
    },

    // === DEVELOPER TOOLS ===
    {
        id: 'json-to-xml',
        title: 'JSON to XML',
        description: 'Convert JSON data to XML format',
        icon: '🔗',
        category: 'dev',
        href: '/json-to-xml',
        color: 'slate',
    },
    {
        id: 'yaml-to-json',
        title: 'YAML to JSON',
        description: 'Convert configuration YAML to JSON',
        icon: '⚙️',
        category: 'dev',
        href: '/yaml-to-json',
        color: 'slate',
    },
    {
        id: 'sql-to-csv',
        title: 'SQL to CSV',
        description: 'Export database SQL to CSV files',
        icon: '🗄️',
        category: 'dev',
        href: '/sql-to-csv',
        color: 'slate',
    },

    // === WEB & MARKUP ===
    {
        id: 'html-to-pdf',
        title: 'HTML to PDF',
        description: 'Convert web pages to PDF documents',
        icon: '🌐',
        category: 'web',
        href: '/html-to-pdf',
        color: 'indigo',
    },
    {
        id: 'markdown-to-pdf',
        title: 'Markdown to PDF',
        description: 'Convert MD files to styled PDF',
        icon: '📝',
        category: 'web',
        href: '/markdown-to-pdf',
        color: 'indigo',
    },

    // === ORGANIZE & ARCHIVE ===
    {
        id: 'merge',
        title: 'Merge PDF',
        description: 'Combine multiple PDFs into one',
        icon: '🔗',
        category: 'organize',
        href: '/merge',
        color: 'purple',
    },
    {
        id: 'split',
        title: 'Split PDF',
        description: 'Separate pages or split PDF documents',
        icon: '✂️',
        category: 'organize',
        href: '/split',
        color: 'purple',
    },
    {
        id: 'zip-to-pdf',
        title: 'ZIP to PDF',
        description: 'Convert archive of documents to a single PDF',
        icon: '🗄️',
        category: 'organize',
        href: '/zip-to-pdf',
        color: 'purple',
    },

    // === OPTIMIZE & REPAIR ===
    {
        id: 'compress',
        title: 'Compress PDF',
        description: 'Reduce file size without quality loss',
        icon: '🗜️',
        category: 'optimize',
        href: '/compress',
        color: 'emerald',
    },
    {
        id: 'repair',
        title: 'Repair PDF',
        description: 'Recover data from corrupted PDF files',
        icon: '🔧',
        category: 'optimize',
        href: '/repair',
        color: 'emerald',
    },

    // === EDIT & PAGE OPS ===
    {
        id: 'rotate',
        title: 'Rotate PDF',
        description: 'Rotate PDF pages permanently',
        icon: '↻',
        category: 'edit',
        href: '/rotate',
        color: 'orange',
    },
    {
        id: 'watermark',
        title: 'Watermark PDF',
        description: 'Add text/image watermarks to your PDF',
        icon: '💧',
        category: 'edit',
        href: '/watermark',
        color: 'orange',
    },
    {
        id: 'page-numbers',
        title: 'Page Numbers',
        description: 'Add or customize PDF page numbering',
        icon: '🔢',
        category: 'edit',
        href: '/page-numbers',
        color: 'orange',
    },

    // === SECURITY & LEGAL ===
    {
        id: 'protect',
        title: 'Protect PDF',
        description: 'Encrypt your PDF with a password',
        icon: '🔒',
        category: 'secure',
        href: '/protect',
        color: 'indigo',
    },
    {
        id: 'unlock',
        title: 'Unlock PDF',
        description: 'Remove encryption and passwords',
        icon: '🔓',
        category: 'secure',
        href: '/unlock',
        color: 'indigo',
    },

    // === MEDIA & VIDEO ===
    {
        id: 'video-to-mp3',
        title: 'Video to MP3',
        description: 'Extract audio from video files',
        icon: '🎵',
        category: 'media',
        href: '/video-to-mp3',
        color: 'red',
    },
    {
        id: 'subtitle-to-txt',
        title: 'Subtitle to Text',
        description: 'Convert SRT/VTT to plain text',
        icon: '💬',
        category: 'media',
        href: '/subtitle-to-txt',
        color: 'red',
    },
];
